### ISSUE TITLE
Applet causes high cpu load from polkit, and repeated dbus warnings.

### ISSUE THREAD

**Issue by Trucido** [ccadeptic23/Multi-Core-System-Monitor#4]
not sure why this applet causes this, but it appears there's some dbus service not registered. I've installed the appropriate dependencies, even tried installing gnome-applets to see if it installed any additional dbus services. basically my syslog goes on forever with this, and polkit has high cpu usage. I don't even have the "Net" part of the applet enabled either. errors go away when applet is uninstalled, but come back when installed/enabled again. I'm on Mint 17.1 cinnamon.

May 21 21:05:13 Lyra NetworkManager[1127]: <warn> error requesting auth for org.freedesktop.NetworkManager.wifi.share.open: (8) GDBus.Error:org.freedesktop.DBus.Error.LimitsExceeded: The maximum number of pending replies per connection has been reached
May 21 21:05:13 Lyra NetworkManager[1127]: <warn> error requesting auth for org.freedesktop.NetworkManager.settings.modify.system: (8) GDBus.Error:org.freedesktop.DBus.Error.LimitsExceeded: The maximum number of pending replies per connection has been reached
May 21 21:05:13 Lyra NetworkManager[1127]: <warn> error requesting auth for org.freedesktop.NetworkManager.settings.modify.own: (8) GDBus.Error:org.freedesktop.DBus.Error.LimitsExceeded: The maximum number of pending replies per connection has been reached
May 21 21:05:13 Lyra NetworkManager[1127]: <warn> error requesting auth for org.freedesktop.NetworkManager.settings.modify.hostname: (8) GDBus.Error:org.freedesktop.DBus.Error.LimitsExceeded: The maximum number of pending replies per connection has been reached
May 21 21:05:13 Lyra NetworkManager[1127]: <warn> error requesting auth for org.freedesktop.NetworkManager.enable-disable-network: (8) GDBus.Error:org.freedesktop.DBus.Error.LimitsExceeded: The maximum number of pending replies per connection has been reached
May 21 21:05:13 Lyra NetworkManager[1127]: <warn> error requesting auth for org.freedesktop.NetworkManager.sleep-wake: (8) GDBus.Error:org.freedesktop.DBus.Error.LimitsExceeded: The maximum number of pending replies per connection has been reached
May 21 21:05:13 Lyra NetworkManager[1127]: <warn> error requesting auth for org.freedesktop.NetworkManager.enable-disable-wifi: (8) GDBus.Error:org.freedesktop.DBus.Error.LimitsExceeded: The maximum number of pending replies per connection has been reached
May 21 21:05:13 Lyra NetworkManager[1127]: <warn> error requesting auth for org.freedesktop.NetworkManager.enable-disable-wwan: (8) GDBus.Error:org.freedesktop.DBus.Error.LimitsExceeded: The maximum number of pending replies per connection has been reached
May 21 21:05:13 Lyra NetworkManager[1127]: <warn> error requesting auth for org.freedesktop.NetworkManager.enable-disable-wimax: (8) GDBus.Error:org.freedesktop.DBus.Error.LimitsExceeded: The maximum number of pending replies per connection has been reached
May 21 21:05:13 Lyra NetworkManager[1127]: <warn> error requesting auth for org.freedesktop.NetworkManager.network-control: (8) GDBus.Error:org.freedesktop.DBus.Error.LimitsExceeded: The maximum number of pending replies per connection has been reached
May 21 21:05:13 Lyra NetworkManager[1127]: <warn> error requesting auth for org.freedesktop.NetworkManager.wifi.share.protected: (8) GDBus.Error:org.freedesktop.DBus.Error.LimitsExceeded: The maximum number of pending replies per connection has been reached

**Comment by Trucido** [comment]
well i fixed it by completely disabling the Net portion for now. https://gist.github.com/Trucido/27060659b8f6cd3227cc

**Comment by marko-avlijas** [comment]
How do I apply this fix? I have installed this applet using normal linux mint way. What should I do?

**Comment by deutrino** [comment]
This is still a problem on Linux Mint 17.3, kernel 3.13.0-61-generic x86_64.

Several hundred of the above NetworkManager type of errors will be spewed in a 1-2 second time span into syslog every so often.

**Comment by Trucido** [comment]
@marko-avlijas @gordon-morehouse
maybe I'll fork this eventually and fix it. for now here's instructions to gut out the net portions. (the GUI config still shows net but it's not functional, don't enable it)

here's instructions to patch it: https://gist.github.com/Trucido/72956814bbb6c4e2b79fc688351432af

**Comment by edalquist** [comment]
I'm seeing this as well on: Linux 3.13.0-93-generic #140-Ubuntu SMP

**Comment by marko-avlijas** [comment]
Use the patch provided by trucido 2 posts above this one.
